@startuml
'
' Resource:  Hub
' Source:    TMF777-XXX_FruitBasket-v5.0.0.oas.yaml
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BorderColor<<Extension>> blue
   FontColor<<Extension>> blue
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor<<Resource>> #FCF2E3
   backgroundColor<<SubResource>> #FFFFFFF
   backgroundColor<<SubResourceReference>> #FADADD
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

class Hub  <<Pivot>> {
    {field}callback : String (1)
    {field}href : String (1)
    {field}id : String (1)
    query : String
    @baseType : String
    @schemaLocation : String
    {field}@type : String (1)
}





skinparam legendBackgroundColor #transparent
skinparam legendBorderColor #transparent

legend
 <size:10>(1) : Mandatory property
endlegend

@enduml